version: '3'
services:
  # Постгрес база в отдельном контейнере
  postgres:
    # Устанавливаем готовый образ
    image: postgres 
    # Задаем глобальные переменные для доступа к PG
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../airflow_data/pg_data:/var/lib/postgresql/data

  # Airflow в отдельном контейнере
  airflow:
    # Сборка из Dockerfile
    build: .
    restart: always
    # Определяет порядок запуска сервисов
    # Будем ждать postgres
    depends_on:
      - postgres
    # Пробрасываем порты
    ports:
      - 8001:8080
    # Пробрасываем папку с дагами
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/root/airflow/plugins
      - ../airflow_data/logs:/usr/local/airflow/logs
